[package]
name = "cythan-driver"
version = "0.1.0"
edition = "2018"

[dependencies]
errors = { path = "../errors" }
mir = { path = "../mir" }
lir = { path = "../lir" }
cythan = { path = "../vm" }
new-parser = { path = "../new_parser" }
typer = { path = "../typer" }
hir = { path = "../hir" }
soir = { path = "../soir" }

[dev-dependencies]
either = "1"

[lints]
workspace = true
