[package]
name = "cythan-v4"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lir = { path = "crates/lir" }
mir = { path = "crates/mir" }
cythan = { path = "crates/vm" }
cythan-driver = { path = "crates/driver" }
clap = { version = "4", features = ["derive"] }

[profile.release]
debug = true

[workspace]
members = ["crates/lir", "crates/vm", "crates/mir", "crates/errors", "crates/frontend", "crates/driver"]
