//! Cycle-detecting Cythan VM runner — used by tests so a buggy
//! compiler that produces non-terminating bytecode fails fast and
//! deterministically instead of timing out.
//!
//! # Why not just a step limit?
//!
//! A step ceiling is an arbitrary number that has to be set
//! per-test: too low and slow-but-correct programs flake; too
//! high and a buggy program wastes CI minutes before failing.
//! Worse, neither setting tells you *why* a program failed —
//! "exceeded 5 000 000 steps" might mean "buggy infinite loop"
//! or "legitimately big run".
//!
//! # The metric
//!
//! Cythan is fully deterministic: given an identical
//! `(cases, remaining_input, output_so_far)` triple, the next
//! step is forced. So if any *two* steps in a single execution
//! see the same triple, every step from there on repeats the
//! interval between them — i.e. the program is in a strict
//! cycle and will never terminate. Conversely, a program that
//! terminates will visit each state at most once before
//! reaching its self-stop fixpoint.
//!
//! # The algorithm
//!
//! Brent's cycle-finding algorithm. One snapshot of `(cases,
//! inputs_consumed, bytes_printed)` is held; every time the live
//! state matches it we've found a cycle. The snapshot is
//! refreshed at exponentially-spaced step counts (1, 2, 4, …) so
//! we visit O(log N) snapshots while running N total steps.
//! O(state_size) memory, ≤2x runtime overhead vs. an
//! uninstrumented run, and it terminates as soon as the cycle
//! closes — usually within a few hundred steps for buggy
//! generated bytecode.
//!
//! # Honest non-cycle termination
//!
//! Cythan halts via the `stop` macro, which compiles to an
//! instruction that doesn't change `cases`. The runner detects
//! that as the natural termination signal (`prev == cases`
//! after a step). That stays the primary exit; cycle detection
//! only fires for buggy non-stopping programs.

use std::cell::Cell;
use std::rc::Rc;
use std::sync::Mutex;

use cythan::{Cythan, InterruptedCythan};
use mir::RunContext;

/// Outcome of a cycle-detecting run.
#[derive(Debug)]
pub enum RunOutcome {
    /// Program reached its `stop` fixpoint.
    Halted { steps: usize },
    /// State repeated — program will run forever. Carries the
    /// step count up to the point cycle detection fired and the
    /// length of the detected cycle, both useful for diagnosing
    /// the bug.
    Cycle { steps: usize, cycle_len: usize },
}

/// Run `bytecode` to completion or cycle detection. Inputs come
/// from `ctx.input()`, output goes to `ctx.print()`. Returns
/// `(outcome, ctx)` so tests can inspect captured I/O.
pub fn run_bin_until_done<T: RunContext + 'static>(
    bytecode: &[usize],
    ctx: T,
) -> (RunOutcome, Rc<Mutex<T>>) {
    // Counter cells shared with the print/input closures so we
    // can read them off without bothering the inner ctx with
    // an extra trait method. `Cell` is fine — the closures are
    // single-threaded (`Rc<Mutex<…>>`) and we only touch the
    // counters between VM steps.
    let inputs_consumed = Rc::new(Cell::new(0usize));
    let bytes_printed = Rc::new(Cell::new(0usize));

    let car = Rc::new(Mutex::new(ctx));
    let car_for_print = car.clone();
    let car_for_input = car.clone();
    let car_return = car.clone();
    let inputs_for_input = inputs_consumed.clone();
    let bytes_for_print = bytes_printed.clone();

    let mut machine = InterruptedCythan::new(
        bytecode.to_vec(),
        4,
        2 * 2_usize.pow(4) + 3,
        move |a| {
            bytes_for_print.set(bytes_for_print.get() + 1);
            car_for_print.lock().unwrap().print(a);
        },
        move || {
            inputs_for_input.set(inputs_for_input.get() + 1);
            car_for_input.lock().unwrap().input()
        },
    );

    // Brent's algorithm state. The "tortoise" is the snapshot
    // taken at exponentially-growing step counts; the "hare" is
    // the live machine.
    let mut steps = 0usize;
    let mut power = 1usize;
    let mut lambda = 1usize;
    let mut snap_cases = machine.cases.clone();
    let mut snap_inputs = inputs_consumed.get();
    let mut snap_prints = bytes_printed.get();

    loop {
        steps += 1;
        let prev_cases = machine.cases.clone();
        machine.next();

        // Natural halt: the `stop` macro is a self-loop, so the
        // step is a no-op.
        if prev_cases == machine.cases {
            return (RunOutcome::Halted { steps }, car_return);
        }

        // Cycle? Same memory image AND same I/O cursors as the
        // tortoise means every future step from here mirrors the
        // tortoise's path — strict deterministic cycle. Check
        // *before* the snapshot refresh below so a freshly-moved
        // tortoise doesn't trivially match itself.
        if machine.cases == snap_cases
            && inputs_consumed.get() == snap_inputs
            && bytes_printed.get() == snap_prints
        {
            return (
                RunOutcome::Cycle {
                    steps,
                    cycle_len: lambda,
                },
                car_return,
            );
        }

        // Refresh the tortoise at step counts 1, 2, 4, 8, … —
        // O(log N) snapshots over a run of N steps.
        if lambda == power {
            snap_cases = machine.cases.clone();
            snap_inputs = inputs_consumed.get();
            snap_prints = bytes_printed.get();
            power *= 2;
            lambda = 0;
        }
        lambda += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_context::TestContext;
    use either::Either;
    use lir::CompilableInstruction;
    use mir::{Mir, MirCodeBlock, MirState};

    /// Compile a tiny MIR block to the bytecode the VM actually
    /// runs. Goes through the same MIR→LIR→bytecode pipeline as
    /// real programs so the harness exercises bytecode that
    /// matches real-world shape (including the `stop` macro).
    fn bytecode_of(block: MirCodeBlock) -> Vec<usize> {
        let mut state = MirState::default();
        block.to_asm(&mut state);
        state.opt_asm();
        CompilableInstruction::compile_to_binary(state.instructions)
    }

    /// `Mir::Stop` lowers to the `stop` macro, which is the
    /// canonical "no progress" instruction — `prev == cases`
    /// catches it and we exit through `Halted`.
    #[test]
    fn halts_on_stop() {
        let bytecode = bytecode_of(MirCodeBlock(vec![Mir::Stop]));
        let (outcome, _) = run_bin_until_done(&bytecode, TestContext::new(""));
        assert!(
            matches!(outcome, RunOutcome::Halted { .. }),
            "expected Halted, got {:?}",
            outcome
        );
    }

    /// `Set(0, 7); Stop` does observable work then halts.
    /// Confirms the harness reports `Halted` after non-trivial
    /// execution rather than incorrectly tripping cycle detection.
    #[test]
    fn halts_after_doing_work() {
        let bytecode = bytecode_of(MirCodeBlock(vec![
            Mir::Set(20, 7),
            Mir::Set(21, 3),
            Mir::Stop,
        ]));
        let (outcome, _) = run_bin_until_done(&bytecode, TestContext::new(""));
        assert!(
            matches!(outcome, RunOutcome::Halted { .. }),
            "expected Halted, got {:?}",
            outcome
        );
    }

    /// `Loop { Set(s, 1); Set(s, 0); }` — the body writes the
    /// same two values every iteration, so `(cases, io)` repeats.
    /// Without cycle detection this test would never finish.
    #[test]
    fn detects_loop_with_constant_writes() {
        let bytecode = bytecode_of(MirCodeBlock(vec![Mir::Loop(MirCodeBlock(
            vec![Mir::Set(20, 1), Mir::Set(20, 0)],
        ))]));
        let (outcome, _) = run_bin_until_done(&bytecode, TestContext::new(""));
        assert!(
            matches!(outcome, RunOutcome::Cycle { .. }),
            "expected Cycle, got {:?}",
            outcome
        );
    }

    /// `MapValue` with the canonical inc table writes
    /// `dst = src + 1 mod 16`. Lowers to the tight `inc(dst)`
    /// macro — verified by checking the program halts and the
    /// destination cell holds the expected value.
    #[test]
    fn map_value_inc_table_runs_to_completion() {
        // src = 5; dst = src + 1 = 6; print dst; stop.
        // Memory layout: slot 20 = src, slot 21 = dst.
        let bytecode = bytecode_of(MirCodeBlock(vec![
            Mir::Set(20, 5),
            Mir::MapValue(20, 21, mir::INC_TABLE),
            // Spread the U4 across reg 1 (high) and reg 2 (low) for `print`.
            Mir::Set(22, 0),
            Mir::WriteRegister(1, Either::Right(22)),
            Mir::WriteRegister(2, Either::Right(21)),
            Mir::WriteRegister(0, Either::Left(1)),
            Mir::Stop,
        ]));
        let (outcome, ctx) = run_bin_until_done(&bytecode, TestContext::new(""));
        assert!(
            matches!(outcome, RunOutcome::Halted { .. }),
            "expected Halted, got {:?}",
            outcome
        );
        // Output is the byte 6 — not necessarily printable, but its
        // raw value tells us the lookup worked.
        assert_eq!(ctx.lock().unwrap().print, vec![6]);
    }

    /// `MapValue` on `src == 0` — exercises the cell-16
    /// indirection path the macro uses (cell-0 holds the PC, so
    /// input 0 is rerouted to cell 16). Easy to break when
    /// generalising the inc/dec template.
    #[test]
    fn map_value_zero_input_uses_cell_16() {
        let mut table = [0u8; 16];
        table[0] = 11;
        let bytecode = bytecode_of(MirCodeBlock(vec![
            Mir::Set(20, 0),
            Mir::MapValue(20, 21, table),
            Mir::Set(22, 0),
            Mir::WriteRegister(1, Either::Right(22)),
            Mir::WriteRegister(2, Either::Right(21)),
            Mir::WriteRegister(0, Either::Left(1)),
            Mir::Stop,
        ]));
        let (outcome, ctx) = run_bin_until_done(&bytecode, TestContext::new(""));
        assert!(matches!(outcome, RunOutcome::Halted { .. }));
        assert_eq!(ctx.lock().unwrap().print, vec![11]);
    }

    /// Output of zero (`T[X] == 0`) — exercises the `'#0 = 16`
    /// label substitution. If the emitter writes literal `0`
    /// instead of `'#0`, dispatch quietly clobbers cell 0 (the
    /// PC).
    #[test]
    fn map_value_zero_output_uses_pound_zero_label() {
        let mut table = [5u8; 16];
        table[3] = 0;
        let bytecode = bytecode_of(MirCodeBlock(vec![
            Mir::Set(20, 3),
            Mir::MapValue(20, 21, table),
            Mir::Set(22, 0),
            Mir::WriteRegister(1, Either::Right(22)),
            Mir::WriteRegister(2, Either::Right(21)),
            Mir::WriteRegister(0, Either::Left(1)),
            Mir::Stop,
        ]));
        let (outcome, ctx) = run_bin_until_done(&bytecode, TestContext::new(""));
        assert!(matches!(outcome, RunOutcome::Halted { .. }));
        assert_eq!(ctx.lock().unwrap().print, vec![0]);
    }

    /// `MapValue` with a non-canonical 2-output (boolean-shaped)
    /// table — exercises the fall-back Match-of-Set bytecode
    /// emission. Catches bugs there before whole-program tests
    /// would.
    #[test]
    fn map_value_boolean_table_runs_to_completion() {
        // Truth table: 1 if input == 7, else 0. Test with input 7.
        let mut table = [0u8; 16];
        table[7] = 1;
        let bytecode = bytecode_of(MirCodeBlock(vec![
            Mir::Set(20, 7),
            Mir::MapValue(20, 21, table),
            Mir::Set(22, 0),
            Mir::WriteRegister(1, Either::Right(22)),
            Mir::WriteRegister(2, Either::Right(21)),
            Mir::WriteRegister(0, Either::Left(1)),
            Mir::Stop,
        ]));
        let (outcome, ctx) = run_bin_until_done(&bytecode, TestContext::new(""));
        assert!(
            matches!(outcome, RunOutcome::Halted { .. }),
            "expected Halted, got {:?}",
            outcome
        );
        assert_eq!(ctx.lock().unwrap().print, vec![1]);
    }
}
