use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum Token {
    Number(i64),
    Ident(String),
    TypeName(String),
    String(String),
    Char(char),

    // Keywords
    Struct,
    Enum,
    Extension,
    Impl,
    Trait,
    Type,
    Fn,
    Mut,
    If,
    Else,
    Loop,
    Break,
    Continue,
    Return,
    Match,
    True,
    False,
    Const,
    For,
    In,
    While,
    As,
    Use,
    Let,
    SelfValue,

    // Symbols
    Dot,
    Comma,
    Colon,
    Semicolon,
    Assign,
    EqEq,
    NotEq,
    Gt,
    Lt,
    GtEq,
    LtEq,
    PathSep,
    FatArrow,
    Underscore,
    AndAnd,
    OrOr,
    Plus,
    Minus,
    PlusAssign,
    MinusAssign,
    Bang,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Token::Number(n) => write!(f, "{}", n),
            Token::Ident(s) => write!(f, "{}", s),
            Token::TypeName(s) => write!(f, "{}", s),
            Token::String(s) => write!(f, "\"{}\"", s),
            Token::Char(c) => write!(f, "'{}'", c),
            Token::Struct => write!(f, "struct"),
            Token::Enum => write!(f, "enum"),
            Token::Extension => write!(f, "extension"),
            Token::Impl => write!(f, "impl"),
            Token::Trait => write!(f, "trait"),
            Token::Type => write!(f, "type"),
            Token::Fn => write!(f, "fn"),
            Token::Mut => write!(f, "mut"),
            Token::If => write!(f, "if"),
            Token::Else => write!(f, "else"),
            Token::Loop => write!(f, "loop"),
            Token::Break => write!(f, "break"),
            Token::Continue => write!(f, "continue"),
            Token::Return => write!(f, "return"),
            Token::Match => write!(f, "match"),
            Token::True => write!(f, "true"),
            Token::False => write!(f, "false"),
            Token::Const => write!(f, "const"),
            Token::For => write!(f, "for"),
            Token::In => write!(f, "in"),
            Token::While => write!(f, "while"),
            Token::As => write!(f, "as"),
            Token::Use => write!(f, "use"),
            Token::Let => write!(f, "let"),
            Token::SelfValue => write!(f, "self"),
            Token::Dot => write!(f, "."),
            Token::Comma => write!(f, ","),
            Token::Colon => write!(f, ":"),
            Token::Semicolon => write!(f, ";"),
            Token::Assign => write!(f, "="),
            Token::EqEq => write!(f, "=="),
            Token::NotEq => write!(f, "!="),
            Token::Gt => write!(f, ">"),
            Token::Lt => write!(f, "<"),
            Token::GtEq => write!(f, ">="),
            Token::LtEq => write!(f, "<="),
            Token::PathSep => write!(f, "::"),
            Token::FatArrow => write!(f, "=>"),
            Token::Underscore => write!(f, "_"),
            Token::AndAnd => write!(f, "&&"),
            Token::OrOr => write!(f, "||"),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::PlusAssign => write!(f, "+="),
            Token::MinusAssign => write!(f, "-="),
            Token::Bang => write!(f, "!"),
            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::LBrace => write!(f, "{{"),
            Token::RBrace => write!(f, "}}"),
            Token::LBracket => write!(f, "["),
            Token::RBracket => write!(f, "]"),
        }
    }
}
